stitching:
  model_name: lightglue_dinov3_vits
  device: cpu
  max_allowed_rotation_angle: 50
  min_matching_threshold: 20
  y_distribution_num_bins: 3
  y_distribution_min_points_per_bin: 5
  y_distribution_min_bins: 2
  verbose: false
  blending: false
  straightening: true
  mask_warp_max_dim: 2048
  final_image_max_dim: 4096
  iou_threshold: 0.02
  horizontal_overlap_threshold: 0.02
  vertical_separation_threshold: 0.60
  unique_frac_threshold: 0.2
  lightglue_weights:
    lightglue_dinov3_vits: weights/lightglue/lightglue_dino.pth
    lightglue_dinov3_vitb: weights/lightglue/lightglue_dino_vitb.pth
    lightglue_dinov3_vitl: weights/lightglue/lightglue_dino_vitl.pth
    lightglue_dinov2_vits: weights/lightglue/lightglue_dinov2.pth
  lightglue_ransac_threshold: 10.0
  lightglue_min_matches: 5
  lightglue_min_matching_threshold: 4
  lightglue_model:
    input_dim: 384
    descriptor_dim: 256
    n_layers: 9
    num_heads: 4
    flash: false
    filter_threshold: 0.1
    depth_confidence: -1
    width_confidence: -1
  gluestick_max_keypoints: 1000
  gluestick_max_lines: 300
  gluestick_ransac_threshold: 5.0
  gluestick_max_edge: 1024
  lightgluestick_max_keypoints: 2048
  lightgluestick_max_lines: 250
  lightgluestick_ransac_threshold: 5.0
  lightgluestick_max_edge: 1024
  roma_num_samples: 5000
  roma_setting: fast
  roma_ransac_threshold: 5.0

embeddings:
  crop_margin: 10
  variant: lightglue_dinov3_vits
  dino_weights:
    lightglue_dinov3_vits: weights/dino/dinov3_vits16_pretrain.pth
    lightglue_dinov3_vitb: weights/dino/dinov3_vitb16_pretrain.pth
    lightglue_dinov3_vitl: weights/dino/dinov3_vitl16_pretrain.pth
    lightglue_dinov2_vits: weights/dino/dinov2_vits14_pretrain.pth

detector:
  sku_yolo_weights: weights/sku_yolo/best_sku110k.pt
  confidence: 0.25

benchmark:
  data_root: data/benchmark
  matching_threshold: 0.4
